
/*
DROP TABLE IF EXISTS emp;

-- 테이블 레벨에서 사용할 CHARACTER SET, COLLATE 값을 지정하면
-- test 디비에서도 한글을 사용할 수 있다.
CREATE TABLE emp (
	empno INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	ename VARCHAR(100),
	job VARCHAR(100),
	sal DOUBLE
) ENGINE=InnoDB CHARACTER SET 'utf8' COLLATE 'utf8_general_ci';

--DROP TABLE IF EXISTS member;

--CREATE TABLE member SELECT * FROM emp WHERE 1=0;
*/

DROP TABLE IF EXISTS NOTE;
DROP TABLE IF EXISTS APPROVAL;
DROP TABLE IF EXISTS DOC;
DROP TABLE IF EXISTS EMP;
DROP TABLE IF EXISTS DEPT;

CREATE TABLE DEPT (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '부서코드', 
  NAME varchar(20) NOT NULL UNIQUE COMMENT '부서명', 
  CHIEF INT NULL COMMENT '부서장',
  UP_ID INT NULL COMMENT '상위부서코드',
  FOREIGN KEY(UP_ID) REFERENCES DEPT(ID) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='부서,팀관리';

CREATE TABLE EMP (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT 'EMP ID',
  nick varchar(20) NOT NULL COMMENT '사용자 ID',
  PW varchar(20) NOT NULL COMMENT '사용자 PW',
  NAME varchar(20) NOT NULL COMMENT '사용자명',
  PHONE varchar(12) NOT NULL COMMENT '휴대폰번호',
  EMAIL varchar(50) NOT NULL COMMENT '이메일',
  DEPT_ID INT NOT NULL COMMENT '부서 ID',  
  FOREIGN KEY(DEPT_ID) REFERENCES DEPT(ID) ON UPDATE CASCADE      
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='사원관리';

CREATE TABLE DOC (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '문서번호',
  TITLE varchar(1000) NOT NULL COMMENT '제목',
  BODY varchar(5000) NOT NULL COMMENT '내용',
  PUBLISH BOOLEAN NOT NULL DEFAULT FALSE COMMENT '공지여부',
  AUTHOR INT NOT NULL COMMENT '작성자',
  STAMP DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  FOREIGN KEY(AUTHOR) REFERENCES EMP(ID) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='전자결재';

CREATE TABLE APPROVAL (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '승인번호',
  DOC_ID INT NOT NULL COMMENT '문서번호',
  APPROVER INT NOT NULL COMMENT '결재자',
  STAT INT NOT NULL DEFAULT 0 COMMENT '결재여부',
  REASON varchar(1000) NULL COMMENT '비고(반려사유)',
  STAMP DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일자',  
  FOREIGN KEY(DOC_ID) REFERENCES DOC(ID) ON UPDATE CASCADE,
  FOREIGN KEY(APPROVER) REFERENCES EMP(ID) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='전자결재 마스터';

CREATE TABLE NOTE (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '글번호',
  TITLE varchar(1000) NOT NULL COMMENT '제목',
  BODY varchar(5000) NOT NULL COMMENT '내용',  
  AUTHOR INT NOT NULL COMMENT '등록자',
  STAMP DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '등록일시',
  FOREIGN KEY(AUTHOR) REFERENCES EMP(ID) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='게시판';
